apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: https-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: professional-website-static-address
    networking.gke.io/managed-certificates: professional-website-certificate
spec:
  backend:
    serviceName: professional-website-web-server-service
    servicePort: 80
