apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: https-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  rules:
    - host: jeremiahvaughan.com
      http:
        paths:
          - path: /
            backend:
              serviceName: professional-website-web-server-service
              servicePort: 80
#    - host: alexalpert.com
#      http:
#        paths:
#          - path: /*
#            backend:
#              serviceName: professional-website-web-server-service
#              servicePort: 80
    - http:
        paths:
          - path: /
            backend:
              serviceName: professional-website-web-server-service
              servicePort: 80
  tls:
    - hosts:
      - jeremiahvaughan.com
      secretName: jeremiah-vaughan-net-tls


