apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  labels:
    name: database-deployment
    app: professional-website
spec:
  replicas: 3
  selector:
    matchLabels:
      name: database-pod
      app: professional-website
  template:
    metadata:
      labels:
        name: database-pod
        app: professional-website
    spec:
      containers:
        - name: web-server
          image: mariadb
          ports:
            - containerPort: 3306
