apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-storage-space
  labels:
    name: database-storage-space
    app: professional-website
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  labels:
    name: database-deployment
    app: professional-website
spec:
  replicas: 1
  selector:
    matchLabels:
      name: database-pod
      app: professional-website
  template:
    metadata:
      labels:
        name: database-pod
        app: professional-website
    spec:
      containers:
        - name: database-pod
          image: mariadb/server
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef: db-credentials
                  key: db-user-root-password
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef: db-credentials
                  key: db-username
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef: db-credentials
                  key: db-user-password
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef: db-credentials
                  key: db-name
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: site-db
          ports:
            - containerPort: 3306
              name: mysql
      volumes:
        - name: site-db
          persistentVolumeClaim:
            claimName: database-storage-space
