apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  labels:
    name: database-deployment
    app: professional-website
spec:
  replicas: 1
  selector:
    matchLabels:
      name: database-pod
      app: professional-website
  template:
    metadata:
      labels:
        name: database-pod
        app: professional-website
    spec:
      containers:
        - name: database-pod
          image: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-user-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-name
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: site-db
          ports:
            - containerPort: 5432
              name: postgres
      volumes:
        - name: site-db
          emptyDir: {}


