apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    name: web-server-pod
    app: professional-website
spec:

  containers:
    - name: web-server
      image: nginx
      ports:
        - containerPort: 80
