apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-storage-space
  labels:
    name: wordpress-storage-space
    app: professional-website
spec:
  accessModes:
     - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
  labels:
    name: web-server-deployment
    app: professional-website
spec:
  replicas: 3
  selector:
    matchLabels:
      name: web-server-pod
      app: professional-website
  template:
    metadata:
      labels:
        name: web-server-pod
        app: professional-website
    spec:
      containers:
        - name: web-server
          image: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: database-service
            - name: WORDPRESS_DB_USER
              value:
            - name: WORDPRESS_DB_PASSWORD
              value:
            - name: WORDPRESS_DB_NAME
              value:
          volumeMounts:
            - name: wordpress-storage
              mountPath: /var/www/html
          ports:
            - containerPort: 80
      volumes:
        - name: wordpress-storage
          persistentVolumeClaim:
            claimName: wordpress-storage-space
