apiVersion: v1
kind: Service
metadata:
  name: professional-website-service
  labels:
    name: professional-website-service
    app: professional-website
spec:
  type: LoadBalancer
  selector:
    name: web-server-pod
    app: professional-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
