apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels:
    name: database-service
    app: professional-website
spec:
  selector:
    name: database-pod
    app: professional-website
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
