apiVersion: v1
kind: Service
metadata:
  name: professional-website-web-server
  labels:
    name: professional-website-web-server
    app: professional-website
spec:
  type: LoadBalancer
  selector:
    name: web-server-pod
    app: professional-website
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
